# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title GetRdConsumer
#' @name GetRdConsumer
#' @description Creates an Rcpp::XPtr<RdKafka::Consumer>. For more details on options \link{https://github.com/edenhill/librdkafka/blob/master/CONFIGURATION.md}
#' @param keys a character vector indicating option keys to parameterize the RdKafka::Consumer
#' @param values a character vector indicating option values to parameterize the RdKafka::Consumer. Must be of same length as keys.
#' @return a Rcpp::XPtr<RdKafka::Consumer>
GetRdConsumer <- function(keys, values) {
    .Call('_fRanz_GetRdConsumer', PACKAGE = 'fRanz', keys, values)
}

#' @title RdSubscribe
#' @name RdSubscribe
#' @description A method to register a consumer with a set amount of topics as consumers. 
#' This is important so the broker can track offsets and register it in a consumer group
#' @param consumerPtr a reference to a Rcpp::XPtr<RdKafka::KafkaConsumer>
#' @param Rtopics a character vector listing the topics to subscribe to
#' @return the int representation of the librdkafka error code of the response to subscribe. 0 is good
RdSubscribe <- function(consumerPtr, Rtopics) {
    .Call('_fRanz_RdSubscribe', PACKAGE = 'fRanz', consumerPtr, Rtopics)
}

#' @title KafkaConsume
#' @name KafkaConsume
#' @description Consume a fixed number of results from whatever topic(s)
#'              the provided consumer is subscribed to.
#' @param consumerPtr a reference to a Rcpp::XPtr<RdKafka::KafkaConsumer>
#' @param numResults how many results should be consumed before returning. Will return early if offset is at maximum
#' @return a list of length numResults with values list(key=key,value=value)
KafkaConsume <- function(consumerPtr, numResults) {
    .Call('_fRanz_KafkaConsume', PACKAGE = 'fRanz', consumerPtr, numResults)
}

#' @title GetRdProducer
#' @name GetRdProducer
#' @description Creates an Rcpp::XPtr<RdKafka::Producer>. For more details on options \link{https://github.com/edenhill/librdkafka/blob/master/CONFIGURATION.md}
#' @param keys a character vector indicating option keys to parameterize the RdKafka::Producer
#' @param values a character vector indicating option values to parameterize the RdKafka::Producer. Must be of same length as keys.
#' @return a Rcpp::XPtr<RdKafka::Producer>
GetRdProducer <- function(keys, values) {
    .Call('_fRanz_GetRdProducer', PACKAGE = 'fRanz', keys, values)
}

#' @title KafkaProduce
#' @name KafkaProduce
#' @description Produces key/values to a particular topic on a particular partition
#' @param producer_pointer a Rcpp::XPtr<RdKafka::Producer>
#' @param topic a string indicating the topic to produce to
#' @param partition an integer indicating the partition to produce to
#' @param keys a character vector for all the keys for the messages
#' @param values a character vector for all the values for the messages. Must be of same length as keys
#' @return returns the number of messages succesfully sent
KafkaProduce <- function(producer_pointer, topic, partition, keys, values) {
    .Call('_fRanz_KafkaProduce', PACKAGE = 'fRanz', producer_pointer, topic, partition, keys, values)
}

